---
version: '3'
services:
  freqtrade:
    image: freqtrade_ta
    # image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
       context: .
       dockerfile: "./Dockerfile.ta"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
       - "0.0.0.0:8080:8080"
       - "0.0.0.0:8081:8081"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_hv45.log
      --db-url sqlite:////freqtrade/user_data/tradesv3_binhv45.dryrun.sqlite
      --config /freqtrade/user_data/config_001_new.json
      --strategy BinHV45
